# Generated by Django 2.0 on 2017-12-26 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('6d338fc6-ea21-11e7-81a4-8c85903bda80'), max_length=40),
        ),
    ]
