# Generated by Django 2.0 on 2017-12-26 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0002_api_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('96768c62-ea21-11e7-aba8-8c85903bda80'), max_length=40),
        ),
    ]
