# Generated by Django 2.0 on 2017-12-28 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0003_auto_20171226_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('c961b0ee-eb83-11e7-afdf-8c85903bda80'), max_length=40),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
