# Generated by Django 2.0 on 2017-12-28 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0004_auto_20171228_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('d21c0d5a-ebbb-11e7-99db-8c85903bda80'), max_length=40),
        ),
        migrations.AlterField(
            model_name='api',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
