# Generated by Django 2.0 on 2017-12-28 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0005_auto_20171228_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('3263566e-ebbc-11e7-b1b5-8c85903bda80'), max_length=40),
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='note',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='path',
            field=models.CharField(max_length=128),
        ),
    ]
