# Generated by Django 2.0 on 2018-01-02 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0006_auto_20171228_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('9f301b80-ef70-11e7-b3ff-8c85903bda80'), max_length=40),
        ),
    ]
