# Generated by Django 2.0 on 2018-01-02 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0007_auto_20180102_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('d6073f1c-ef70-11e7-ae38-8c85903bda80'), max_length=40),
        ),
    ]
