# Generated by Django 2.0 on 2018-01-02 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0008_auto_20180102_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('da488ed2-ef70-11e7-94ad-8c85903bda80'), max_length=40),
        ),
    ]
