# Generated by Django 2.0 on 2018-01-02 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0009_auto_20180102_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('7c1e41ac-ef71-11e7-a067-8c85903bda80'), max_length=40),
        ),
    ]
