# Generated by Django 2.0 on 2018-01-02 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0010_auto_20180102_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('9d4a9cfe-ef71-11e7-8026-8c85903bda80'), max_length=40),
        ),
    ]
