# Generated by Django 2.0 on 2018-01-02 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0011_auto_20180102_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=uuid.UUID('2d66a224-ef72-11e7-81c8-8c85903bda80'), max_length=40),
        ),
    ]
