# Generated by Django 2.0 on 2018-02-24 08:39

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(default='', max_length=512, null=True)),
                ('status', models.IntegerField(default=0)),
                ('responseJson', models.TextField(blank=True, default='{}', null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, backend.models.Dictable),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(default='', max_length=512, null=True)),
                ('status', models.IntegerField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('apis', models.ManyToManyField(to='backend.Api')),
            ],
            bases=(models.Model, backend.models.Dictable),
        ),
        migrations.CreateModel(
            name='ResTemplate',
            fields=[
                ('res_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(default='', max_length=512, null=True)),
                ('mimeType', models.IntegerField(default=0)),
                ('responseJson', models.TextField(blank=True, default='{}', null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, backend.models.Dictable),
        ),
        migrations.AddField(
            model_name='project',
            name='responseTemplates',
            field=models.ManyToManyField(to='backend.ResTemplate'),
        ),
    ]
