# Generated by Django 2.0 on 2018-01-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(default='', max_length=512, null=True)),
                ('status', models.IntegerField(default=0)),
                ('responseJson', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(default='', max_length=512, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
