# Generated by Django 2.0 on 2018-01-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
