# Generated by Django 2.0 on 2018-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
