# Generated by Django 2.0 on 2018-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180201_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updateTime',
            field=models.DateTimeField(),
        ),
    ]
