# Generated by Django 2.0 on 2018-02-01 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180201_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
